---
- name: Fetch configuration from Cisco switch
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Get the running configuration from the old switch
      cisco.ios.ios_command:
        commands:
          - show running-config
        provider:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          authorize: yes
          auth_pass: "{{ ansible_password }}"
      register: config_output

    - name: Save config to local file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: ./config_backup.txt
      delegate_to: localhost

